# -*- coding: utf-8 -*-
{   'active': False,
    'author': 'No author.',
    'category': 'base.module_category_hidden',
    'demo_xml': [],
    'depends': [u'account'],
    'description': 'No documented',
    'init_xml': [],
    'installable': True,
    'license': 'AGPL-3',
    'name': 'coop',
    'test': [],
    'update_xml': [   u'security/coop_group.xml',
                      u'view/cooperative_view.xml',
                      u'view/associate_view.xml',
                      u'view/topic_view.xml',
                      u'view/book_view.xml',
                      u'view/letter_view.xml',
                      u'view/partner_view.xml',
                      u'view/proposal_view.xml',
                      u'view/meeting_view.xml',
                      u'data/cooperative_properties.xml',
                      u'data/associate_properties.xml',
                      u'data/topic_properties.xml',
                      u'data/book_properties.xml',
                      u'data/letter_properties.xml',
                      u'data/partner_properties.xml',
                      u'data/proposal_properties.xml',
                      u'data/meeting_properties.xml',
                      u'data/cooperative_track.xml',
                      u'data/associate_track.xml',
                      u'data/topic_track.xml',
                      u'data/book_track.xml',
                      u'data/letter_track.xml',
                      u'data/partner_track.xml',
                      u'data/proposal_track.xml',
                      u'data/meeting_track.xml',
                      u'workflow/proposal_workflow.xml',
                      u'workflow/letter_workflow.xml',
                      'security/ir.model.access.csv',
                      u'view/coop_menuitem.xml'],
    'version': 'No version',
    'website': ''}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
